name: e2e cypress

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install -g @angular/cli@11.2.0
      - run: npm install

      - run: npm start

      - uses: cypress-io/github-action@v2
